### PR TITLE
Beijing Housing GBM

### PR DESCRIPTION
**Pull request by ishwang1**
Preparing the dataset, "lianjia.RData". Changing dependent variable from "totalPrice" to "price", and choosing reasonable independent variables. R-squared of GBM prediction = 0.9295538; R-squared of LM prediction = 0.8445908.

### CODE REVIEW

**Comment by zhentaoshi** [comment]
Thank you. I will review it. 

We might be able to improve it further more by searching the tuning parameters.

**Comment by ishwang1** [comment]
Ok, I will try different tuning parameters!

**Comment by zhentaoshi** [comment]
The tuning parameters can be done more conveniently in the function `train` in caret via the argument `tuneGrid`.

In your tentative experiment, you can use a subsample. It would take too much time in the whole sample.

**Comment by ishwang1** [comment]
Ok, get it! Thanks a lot for reminding!

**Pull request merged**
